/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/context/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Context */
        post: operations["validate_context_api_context_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/insertion-sort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo */
        get: operations["demo_api_demo_insertion_sort_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Feedback */
        post: operations["feedback_api_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/{interaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Feedback */
        delete: operations["delete_feedback_api_feedback__interaction_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrieve */
        post: operations["retrieve_api_retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tutor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tutor */
        post: operations["tutor_api_tutor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Usage */
        post: operations["usage_api_usage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_api_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatTurn */
        ChatTurn: {
            /** Content */
            content: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
        };
        /** Diagnostic */
        Diagnostic: {
            /**
             * Code
             * @default syntax
             */
            code: string;
            /** Column */
            column: number;
            /** Line */
            line: number;
            /** Message */
            message: string;
            /**
             * Severity
             * @default error
             * @enum {string}
             */
            severity: "error" | "warning";
        };
        /** ExecutionContext */
        ExecutionContext: {
            /**
             * Algorithm
             * @default
             */
            algorithm: string;
            /** Arrays */
            arrays?: {
                [key: string]: components["schemas"]["JsonValue"][];
            };
            /**
             * Code
             * @default
             */
            code: string;
            /** Current Line */
            current_line?: number | null;
            /**
             * Language Version
             * @default avp-repository-v1
             */
            language_version: string;
            /**
             * Phase
             * @default unknown
             * @enum {string}
             */
            phase: "before" | "after" | "unknown";
            /** Recent Events */
            recent_events?: components["schemas"]["ExecutionEvent"][];
            /**
             * Run Id
             * @default
             */
            run_id: string;
            /** Step */
            step?: number | null;
            /** Variables */
            variables?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
        };
        /** ExecutionEvent */
        ExecutionEvent: {
            /** Description */
            description: string;
            /** Details */
            details?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Indices */
            indices?: number[];
            /** Kind */
            kind: string;
            /** Line */
            line?: number | null;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Comment
             * @default
             */
            comment: string;
            /** Interaction Id */
            interaction_id: string;
            /**
             * Rating
             * @enum {string}
             */
            rating: "helpful" | "incorrect" | "too_much_answer" | "too_vague" | "missing_context";
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Query */
            query: string;
        };
        /** GenerateResponse */
        GenerateResponse: {
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Generated Code */
            generated_code?: string | null;
            /**
             * Retrieved Functions
             * @default []
             */
            retrieved_functions: components["schemas"]["RetrievedFunction"][];
            validation?: components["schemas"]["ValidationResult"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Knowledge Version
             * @default
             */
            knowledge_version: string;
            /**
             * Model
             * @default
             */
            model: string;
            /**
             * Note
             * @default Configuration status only; model reachability is checked on request.
             */
            note: string;
            /**
             * Provider
             * @default
             */
            provider: string;
            /**
             * Provider Configured
             * @default false
             */
            provider_configured: boolean;
            /**
             * Retriever Loaded
             * @default false
             */
            retriever_loaded: boolean;
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        JsonValue: unknown;
        /** RetrieveRequest */
        RetrieveRequest: {
            /**
             * K
             * @default 2
             */
            k: number;
            /** Query */
            query: string;
        };
        /** RetrieveResponse */
        RetrieveResponse: {
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /**
             * Results
             * @default []
             */
            results: components["schemas"]["RetrievedFunction"][];
        };
        /** RetrievedFunction */
        RetrievedFunction: {
            /** Code */
            code: string;
            /** Function Name */
            function_name: string;
            /** Parameters */
            parameters: string[];
            /** Score */
            score: number;
            /**
             * Source File
             * @default
             */
            source_file: string;
        };
        /** Source */
        Source: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /** Section */
            section: string;
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /** TutorRequest */
        TutorRequest: {
            context?: components["schemas"]["ExecutionContext"] | null;
            /**
             * Feedback Consent
             * @default false
             */
            feedback_consent: boolean;
            /** History */
            history?: components["schemas"]["ChatTurn"][];
            /**
             * Level
             * @default beginner
             * @enum {string}
             */
            level: "beginner" | "intermediate" | "advanced";
            /**
             * Mode
             * @default explain
             * @enum {string}
             */
            mode: "explain" | "hint" | "predict" | "debug";
            /** Question */
            question: string;
        };
        /** TutorResponse */
        TutorResponse: {
            /** Answer */
            answer: string;
            /**
             * Context Status
             * @enum {string}
             */
            context_status: "provided" | "partial" | "missing";
            /**
             * Fallback Used
             * @default false
             */
            fallback_used: boolean;
            /**
             * Harness Version
             * @default
             */
            harness_version: string;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Interaction Id */
            interaction_id?: string | null;
            /** Knowledge Version */
            knowledge_version: string;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Prompt Version */
            prompt_version: string;
            /** Provider */
            provider: string;
            /**
             * Skill
             * @default
             */
            skill: string;
            /** Sources */
            sources?: components["schemas"]["Source"][];
            /** Warnings */
            warnings?: string[];
        };
        /** UsageRequest */
        UsageRequest: {
            /**
             * Algorithm
             * @default
             */
            algorithm: string;
            /**
             * Consent
             * @constant
             */
            consent: true;
            /**
             * Event
             * @enum {string}
             */
            event: "offered" | "opened" | "dismissed" | "asked" | "prediction_correct" | "prediction_incorrect";
        };
        /** ValidateRequest */
        ValidateRequest: {
            /** Code */
            code: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Diagnostics */
            diagnostics?: components["schemas"]["Diagnostic"][];
            /**
             * Execution Verified
             * @default false
             */
            execution_verified: boolean;
            /** Syntax Valid */
            syntax_valid: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    validate_context_api_context_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionContext"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_api_demo_insertion_sort_get: {
        parameters: {
            query?: {
                values?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_api_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_feedback_api_feedback__interaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    retrieve_api_retrieve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrieveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrieveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tutor_api_tutor_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TutorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    usage_api_usage_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_api_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
